global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'fusionpbx test'
    scrape_interval: 1m
    metrics_path: /metrics.txt
    scheme: https
    tls_config:
      insecure_skip_verify: true 
    static_configs:
      - targets: ['172.30.0.210:443']

  - job_name: 'kv umz'
    scrape_interval: 1m
    metrics_path: /metrics.txt
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['172.30.0.195:443']

  - job_name: 'snmp'
    static_configs:
      - targets:
          - 10.5.10.91
          - 10.5.141.2
    metrics_path: /snmp
    params:
      module: [grandstream_custom]
      auth: [public_v2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116

