global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'fusionpbx test'
    scrape_interval: 1m
    metrics_path: /metrics.txt
    scheme: https
    tls_config:
      insecure_skip_verify: true 
    static_configs:
      - targets: ['172.30.0.210:443']

  - job_name: 'kv umz'
    scrape_interval: 1m
    metrics_path: /metrics.txt
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['172.30.0.195:443']

  - job_name: 'freeswitch'
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: /probe
    static_configs:
      - targets:
          - 172.30.0.201:8021
          - 172.30.0.197:8021
          - 172.30.0.207:8021
          - 172.30.0.214:8021
          - 172.30.0.215:8021
          - 172.30.0.195:8021
        labels:
          group: freeswitch
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__address__]
        regex: '(.+):\d+'
        target_label: instance
      - target_label: __address__
        replacement: 172.30.0.212:9724
      - source_labels: [instance]
        regex: '172\.30\.0\.201'
        target_label: server_name
        replacement: 'WG0'
      - source_labels: [instance]
        regex: '172\.30\.0\.197'
        target_label: server_name
        replacement: 'Gate0'
      - source_labels: [instance]
        regex: '172\.30\.0\.207'
        target_label: server_name
        replacement: 'Kv Gate'
      - source_labels: [instance]
        regex: '172\.30\.0\.214'
        target_label: server_name
        replacement: 'Spas'
      - source_labels: [instance]
        regex: '172\.30\.0\.215'
        target_label: server_name
        replacement: 'Int Gate'
      - source_labels: [instance]
        regex: '172\.30\.0\.195'
        target_label: server_name
        replacement: 'Kv UMZ'
    metric_relabel_configs:
      - source_labels: [proxy]
        regex: 'sip:10\.5\.100\.207'
        target_label: name
        replacement: 'Kv Gate'
      - source_labels: [proxy]
        regex: 'sip:10\.5\.101\.195'
        target_label: name
        replacement: 'Lv UMZ'
      - source_labels: [proxy]
        regex: 'sip:10\.5\.102\.195'
        target_label: name
        replacement: 'Dn UMZ'
      - source_labels: [proxy]
        regex: 'sip:10\.5\.104\.195'
        target_label: name
        replacement: 'Od UMZ'

  - job_name: 'snmp'
    static_configs:
      - targets:
          - 10.5.10.91
          - 10.5.141.2
    metrics_path: /snmp
    params:
      module: [grandstream_custom]
      auth: [public_v2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116

