{
 "title": "FreeSWITCH TV",
 "description": "TV kiosk dashboard — FreeSWITCH cluster status at a glance",
 "tags": [
  "freeswitch",
  "voip",
  "tv"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_uptime_seconds{job=\"freeswitch\", server_name=\"Kv Gate\"}",
     "legendFormat": "Kv Gate"
    },
    {
     "expr": "freeswitch_uptime_seconds{job=\"freeswitch\", server_name=\"Gate 0\"}",
     "legendFormat": "Gate0"
    },
    {
     "expr": "freeswitch_uptime_seconds{job=\"freeswitch\", server_name=\"Spas\"}",
     "legendFormat": "Spas"
    },
    {
     "expr": "freeswitch_uptime_seconds{job=\"freeswitch\", server_name=\"Int Gate\"}",
     "legendFormat": "Int Gate"
    },
    {
     "expr": "freeswitch_uptime_seconds{job=\"freeswitch\", server_name=\"WG0\"}",
     "legendFormat": "WG0"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_up{job=\"freeswitch\", server_name=\"Kv Gate\"}",
     "legendFormat": "Kv Gate"
    },
    {
     "expr": "freeswitch_up{job=\"freeswitch\", server_name=\"Gate 0\"}",
     "legendFormat": "Gate0"
    },
    {
     "expr": "freeswitch_up{job=\"freeswitch\", server_name=\"Spas\"}",
     "legendFormat": "Spas"
    },
    {
     "expr": "freeswitch_up{job=\"freeswitch\", server_name=\"Int Gate\"}",
     "legendFormat": "Int Gate"
    },
    {
     "expr": "freeswitch_up{job=\"freeswitch\", server_name=\"WG0\"}",
     "legendFormat": "WG0"
    }
   ]
  },
  {
   "title": "Registrations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_registrations_active{job=\"freeswitch\", server_name=\"Kv Gate\"}",
     "legendFormat": "Kv Gate"
    },
    {
     "expr": "freeswitch_registrations_active{job=\"freeswitch\", server_name=\"Gate 0\"}",
     "legendFormat": "Gate0"
    },
    {
     "expr": "freeswitch_registrations_active{job=\"freeswitch\", server_name=\"Spas\"}",
     "legendFormat": "Spas"
    },
    {
     "expr": "freeswitch_registrations_active{job=\"freeswitch\", server_name=\"Int Gate\"}",
     "legendFormat": "Int Gate"
    },
    {
     "expr": "freeswitch_registrations_active{job=\"freeswitch\", server_name=\"WG0\"}",
     "legendFormat": "WG0"
    }
   ]
  },
  {
   "title": "Active Calls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_calls_active{job=\"freeswitch\", server_name=\"Kv Gate\"}",
     "legendFormat": "Kv Gate"
    },
    {
     "expr": "freeswitch_calls_active{job=\"freeswitch\", server_name=\"Gate 0\"}",
     "legendFormat": "Gate0"
    },
    {
     "expr": "freeswitch_calls_active{job=\"freeswitch\", server_name=\"Spas\"}",
     "legendFormat": "Spas"
    },
    {
     "expr": "freeswitch_calls_active{job=\"freeswitch\", server_name=\"Int Gate\"}",
     "legendFormat": "Int Gate"
    },
    {
     "expr": "freeswitch_calls_active{job=\"freeswitch\", server_name=\"WG0\"}",
     "legendFormat": "WG0"
    }
   ]
  },
  {
   "title": "Active Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_channels_active{job=\"freeswitch\", server_name=\"Kv Gate\"}",
     "legendFormat": "Kv Gate"
    },
    {
     "expr": "freeswitch_channels_active{job=\"freeswitch\", server_name=\"Gate 0\"}",
     "legendFormat": "Gate0"
    },
    {
     "expr": "freeswitch_channels_active{job=\"freeswitch\", server_name=\"Spas\"}",
     "legendFormat": "Spas"
    },
    {
     "expr": "freeswitch_channels_active{job=\"freeswitch\", server_name=\"Int Gate\"}",
     "legendFormat": "Int Gate"
    },
    {
     "expr": "freeswitch_channels_active{job=\"freeswitch\", server_name=\"WG0\"}",
     "legendFormat": "WG0"
    }
   ]
  },
  {
   "title": "Failed Calls (1h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(freeswitch_gateway_failed_calls_in_total{job=\"freeswitch\", server_name=\"Kv Gate\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}[1h]) + increase(freeswitch_gateway_failed_calls_out_total{job=\"freeswitch\", server_name=\"Kv Gate\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}[1h]))",
     "legendFormat": "Kv Gate"
    },
    {
     "expr": "sum(increase(freeswitch_gateway_failed_calls_in_total{job=\"freeswitch\", server_name=\"Gate 0\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}[1h]) + increase(freeswitch_gateway_failed_calls_out_total{job=\"freeswitch\", server_name=\"Gate 0\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}[1h]))",
     "legendFormat": "Gate0"
    },
    {
     "expr": "sum(increase(freeswitch_gateway_failed_calls_in_total{job=\"freeswitch\", server_name=\"Spas\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}[1h]) + increase(freeswitch_gateway_failed_calls_out_total{job=\"freeswitch\", server_name=\"Spas\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}[1h]))",
     "legendFormat": "Spas"
    },
    {
     "expr": "sum(increase(freeswitch_gateway_failed_calls_in_total{job=\"freeswitch\", server_name=\"Int Gate\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}[1h]) + increase(freeswitch_gateway_failed_calls_out_total{job=\"freeswitch\", server_name=\"Int Gate\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}[1h]))",
     "legendFormat": "Int Gate"
    },
    {
     "expr": "sum(increase(freeswitch_gateway_failed_calls_in_total{job=\"freeswitch\", server_name=\"WG0\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}[1h]) + increase(freeswitch_gateway_failed_calls_out_total{job=\"freeswitch\", server_name=\"WG0\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}[1h]))",
     "legendFormat": "WG0"
    }
   ]
  },
  {
   "title": "Gateways",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_gateway_up{job=\"freeswitch\", server_name=\"Kv Gate\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}",
     "legendFormat": "Kv Gate: {{name}}"
    },
    {
     "expr": "freeswitch_gateway_up{job=\"freeswitch\", server_name=\"Gate 0\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}",
     "legendFormat": "Gate 0: {{name}}"
    },
    {
     "expr": "freeswitch_gateway_up{job=\"freeswitch\", server_name=\"Spas\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}",
     "legendFormat": "Spas: {{name}}"
    },
    {
     "expr": "freeswitch_gateway_up{job=\"freeswitch\", server_name=\"Int Gate\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}",
     "legendFormat": "Int Gate: {{name}}"
    },
    {
     "expr": "freeswitch_gateway_up{job=\"freeswitch\", server_name=\"WG0\", name!~\"to_gate_1|to_gate_2|to_gate_3\"}",
     "legendFormat": "WG0: {{name}}"
    }
   ]
  }
 ]
}