{
 "title": "Kv gateways status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Kv UMZ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kv UMZ ↔ Kv Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv UMZ\", name=\"Kv Gate\"}",
       "legendFormat": "Kv UMZ ↔ Kv Gate"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 1 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv UMZ\", name=\"Kv Gate\"}",
       "legendFormat": "Kv UMZ ↔ Kv Gate"
      }
     ]
    },
    {
     "title": "Kv UMZ ↔ Lv UMZ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 160 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv UMZ\", name=\"Lv UMZ\"}",
       "legendFormat": "Kv UMZ ↔ Lv UMZ"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 160 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv UMZ\", name=\"Lv UMZ\"}",
       "legendFormat": "Kv UMZ ↔ Lv UMZ"
      }
     ]
    },
    {
     "title": "Kv UMZ ↔ Dn UMZ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 163 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv UMZ\", name=\"Dn UMZ\"}",
       "legendFormat": "Kv UMZ ↔ Dn UMZ"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 163 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv UMZ\", name=\"Dn UMZ\"}",
       "legendFormat": "Kv UMZ ↔ Dn UMZ"
      }
     ]
    },
    {
     "title": "Kv UMZ ↔ Od UMZ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 166 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv UMZ\", name=\"Od UMZ\"}",
       "legendFormat": "Kv UMZ ↔ Od UMZ"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 166 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv UMZ\", name=\"Od UMZ\"}",
       "legendFormat": "Kv UMZ ↔ Od UMZ"
      }
     ]
    }
   ]
  },
  {
   "title": "Kv Gate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kv Gate ↔ Kv UMZ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_umz\"}",
       "legendFormat": "Kv Gate ↔ Kv UMZ"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 2 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_umz\"}",
       "legendFormat": "Kv Gate ↔ to_umz"
      }
     ]
    },
    {
     "title": "Kv Gate ↔ Gate0",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_gate0\"}",
       "legendFormat": "Kv Gate ↔ Gate0"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 5 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_gate0\"}",
       "legendFormat": "Kv Gate ↔ to_gate0"
      }
     ]
    },
    {
     "title": "Kv Gate ↔ Spas",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_spas\"}",
       "legendFormat": "Kv Gate ↔ Spas"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 8 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_spas\"}",
       "legendFormat": "Kv Gate ↔ to_spas"
      }
     ]
    },
    {
     "title": "Kv Gate ↔ Int Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_int_gate\"}",
       "legendFormat": "Kv Gate ↔ Int Gate"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 11 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_int_gate\"}",
       "legendFormat": "Kv Gate ↔ to_int_gate"
      }
     ]
    },
    {
     "title": "Kv Gate ↔ Lv Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_lv_gate\"}",
       "legendFormat": "Kv Gate ↔ Lv Gate"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 14 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_lv_gate\"}",
       "legendFormat": "Kv Gate ↔ to_lv_gate"
      }
     ]
    },
    {
     "title": "Kv Gate ↔ Dn Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_dn_gate\"}",
       "legendFormat": "Kv Gate ↔ Dn Gate"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 17 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_dn_gate\"}",
       "legendFormat": "Kv Gate ↔ to_dn_gate"
      }
     ]
    },
    {
     "title": "Kv Gate ↔ Od Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_od_gate\"}",
       "legendFormat": "Kv Gate ↔ Od Gate"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 20 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_od_gate\"}",
       "legendFormat": "Kv Gate ↔ to_od_gate"
      }
     ]
    },
    {
     "title": "Kv Gate ↔ SK necm",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_sk_necm\"}",
       "legendFormat": "Kv Gate ↔ SK necm"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 23 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_sk_necm\"}",
       "legendFormat": "Kv Gate ↔ to_sk_necm"
      }
     ]
    },
    {
     "title": "Kv Gate ↔ Cisco 00",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_cisco_00\"}",
       "legendFormat": "Kv Gate ↔ Cisco 00"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 26 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_cisco_00\"}",
       "legendFormat": "Kv Gate ↔ to_cisco_00"
      }
     ]
    },
    {
     "title": "Kv Gate ↔ Cisco 01",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_cisco_01\"}",
       "legendFormat": "Kv Gate ↔ Cisco 01"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 29 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Kv Gate\", name=\"to_cisco_01\"}",
       "legendFormat": "Kv Gate ↔ to_cisco_01"
      }
     ]
    }
   ]
  },
  {
   "title": "Gate0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gate0 ↔ Kv Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Gate0\", name=\"to_kv_gate\"}",
       "legendFormat": "Gate0 ↔ Kv Gate"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 51 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Gate0\", name=\"to_kv_gate\"}",
       "legendFormat": "Gate0 ↔ to_kv_gate"
      }
     ]
    },
    {
     "title": "Gate0 ↔ 10.96.0.200",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Gate0\", name=\"10.96.0.200\"}",
       "legendFormat": "Gate0 ↔ 10.96.0.200"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 54 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Gate0\", name=\"10.96.0.200\"}",
       "legendFormat": "Gate0 ↔ 10.96.0.200"
      }
     ]
    },
    {
     "title": "Gate0 ↔ WG0",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Gate0\", name=\"to_wg0\"}",
       "legendFormat": "Gate0 ↔ WG0"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 57 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Gate0\", name=\"to_wg0\"}",
       "legendFormat": "Gate0 ↔ to_wg0"
      }
     ]
    }
   ]
  },
  {
   "title": "Int Gate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Int Gate ↔ Kv Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Int Gate\", name=\"to_kv_gate\"}",
       "legendFormat": "Int Gate ↔ Kv Gate"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 61 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Int Gate\", name=\"to_kv_gate\"}",
       "legendFormat": "Int Gate ↔ to_kv_gate"
      }
     ]
    },
    {
     "title": "Int Gate ↔ 172.16.9.2",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Int Gate\", name=\"172.16.9.2\"}",
       "legendFormat": "Int Gate ↔ 172.16.9.2"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 64 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Int Gate\", name=\"172.16.9.2\"}",
       "legendFormat": "Int Gate ↔ 172.16.9.2"
      }
     ]
    }
   ]
  },
  {
   "title": "Spas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spas ↔ Kv Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 68 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Spas\", name=\"to_kv_gate\"}",
       "legendFormat": "Spas ↔ Kv Gate"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 68 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"Spas\", name=\"to_kv_gate\"}",
       "legendFormat": "Spas ↔ to_kv_gate"
      }
     ]
    }
   ]
  },
  {
   "title": "WG0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "WG0 ↔ Gate0",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 72 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"WG0\", name=\"gate_0\"}",
       "legendFormat": "WG0 ↔ Gate0"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 72 },
     "targets": [
      {
       "expr": "freeswitch_gateway_up{server_name=\"WG0\", name=\"gate_0\"}",
       "legendFormat": "WG0 ↔ gate_0"
      }
     ]
    }
   ]
  }
 ]
}