{
 "title": "UMZ reg status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Registrations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(freeswitch_registrations_active{server_name=~\".*UMZ\"})",
     "legendFormat": "All DCs"
    }
   ]
  },
  { "title": "Kv UMZ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Registrations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_registrations_active{server_name=\"Kv UMZ\"}",
     "legendFormat": "Kv UMZ"
    }
   ]
  },
  {
   "title": "Registrations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "freeswitch_registrations_active{server_name=\"Kv UMZ\"}",
     "legendFormat": "Kv UMZ"
    }
   ]
  },
  { "title": "Lv UMZ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Registrations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_registrations_active{server_name=\"Lv UMZ\"}",
     "legendFormat": "Lv UMZ"
    }
   ]
  },
  {
   "title": "Registrations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "freeswitch_registrations_active{server_name=\"Lv UMZ\"}",
     "legendFormat": "Lv UMZ"
    }
   ]
  },
  { "title": "Dn UMZ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Registrations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_registrations_active{server_name=\"Dn UMZ\"}",
     "legendFormat": "Dn UMZ"
    }
   ]
  },
  {
   "title": "Registrations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "freeswitch_registrations_active{server_name=\"Dn UMZ\"}",
     "legendFormat": "Dn UMZ"
    }
   ]
  },
  { "title": "Od UMZ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Registrations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_registrations_active{server_name=\"Od UMZ\"}",
     "legendFormat": "Od UMZ"
    }
   ]
  },
  {
   "title": "Registrations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "freeswitch_registrations_active{server_name=\"Od UMZ\"}",
     "legendFormat": "Od UMZ"
    }
   ]
  }
 ]
}