{
 "title": "UMZ extentions",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "extension", "label": "Extension" },
   {
    "name": "server",
    "label": "Server",
    "query": {}
   },
   {
    "name": "event_type",
    "label": "Event",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Extension $extension",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "freeswitch_registration_active{reg_user=\"$extension\"}"
    }
   ]
  },
  {
   "title": "Registration Presence by Server",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "(sum by (server_name) (freeswitch_registration_active{reg_user=\"$extension\", server_name=~\"Kv UMZ|Lv UMZ|Dn UMZ|Od UMZ\"})) or (sum by (server_name) (freeswitch_registration_active{server_name=~\"Kv UMZ|Lv UMZ|Dn UMZ|Od UMZ\"}) * 0)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Registration Events",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"umz-events\", server=~\"$server\", event_type=~\"$event_type\"} | logfmt | extension=~\".*${extension}.*\""
    }
   ]
  }
 ]
}